[book]
authors = ["Charles Low"]
language = "en"
multilingual = false
src = "src"
title = "Linear Algebra Done Right Notes"

[output.html]
copy-fonts = true
default_theme = "navy"
additional-css = ["katex.min.css"]

[output.html.playground]
runnable = false

[preprocessor.katex]
after = ["links"]

[preprocessor.format]
command = "python3 format.py"